#!/usr/bin/env bash
# Pull every fenced ruby block out of the lessons into code/, one file per
# block, with a header naming its source. Regenerate freely; code/ is ignored
# by git because the lessons are the source of truth.
set -euo pipefail
cd "$(dirname "$0")/.."

rm -rf code
count=0

while IFS= read -r qmd; do
  # parts/03-rhythm-and-meter/16-swing-microtiming.qmd -> L16
  base=$(basename "$qmd" .qmd)
  num=${base%%-*}
  outdir="code/L${num}"

  python3 - "$qmd" "$outdir" <<'PY'
import re, sys, pathlib
src, outdir = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
text = src.read_text(encoding="utf-8")
# ```ruby or ```{.ruby ...}
pattern = re.compile(r"^```(?:ruby|\{\.ruby[^}]*\})\s*$(.*?)^```\s*$", re.M | re.S)
blocks = [m for m in pattern.finditer(text)]
if not blocks:
    sys.exit(0)
outdir.mkdir(parents=True, exist_ok=True)
joined, n = [], 0
for m in blocks:
    body = m.group(1)
    line = text[:m.start()].count("\n") + 1
    if "...continued from above" in body:
        joined.append(body)
        continue
    if joined:
        body = "".join(joined) + body
        joined = []
    n += 1
    header = f"# from {src} line {line}\n# regenerated by scripts/extract-code.sh, do not edit\n"
    (outdir / f"{n:02d}.rb").write_text(header + body.lstrip("\n"), encoding="utf-8")
print(f"{src}: {n}")
PY
  count=$((count + 1))
done < <(
  [ -f setup.qmd ] && printf '%s\n' setup.qmd
  find parts appendix -name '*.qmd' 2>/dev/null | sort
)

echo "Scanned $count files. Extracted to code/"
