#!/usr/bin/env python3
"""Generate the book skeleton from the syllabus.

The syllabus tracker in curriculum/ is the single source of truth for what
lessons exist, what they are called, and what each one covers. This script
reads it and produces:

  * the chapter list inside _quarto.yml, between the BEGIN/END markers
  * a stub .qmd for every lesson that does not have one yet
  * a section in appendix/solutions.qmd for every lesson

Existing lesson files are never touched. Once you have written a lesson, this
script leaves it alone forever; it only fills in what is missing. Rerun it
after adding, renaming, or reordering a lesson in the syllabus.

Renaming a lesson changes its filename, which leaves the old stub behind as an
orphan. Orphans are reported, and --prune deletes the ones that are still
untouched outlines. Anything with real content is never deleted.

Usage:
    python3 scripts/gen_book.py            # write files
    python3 scripts/gen_book.py --dry-run  # report what would change
"""

import argparse
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SYLLABUS = ROOT / "curriculum" / "music_theory_through_sonic_pi.html"
CONFIG = ROOT / "_quarto.yml"
SOLUTIONS = ROOT / "appendix" / "solutions.qmd"

BEGIN = "    # BEGIN CHAPTERS (generated by scripts/gen_book.py, do not edit by hand)"
END = "    # END CHAPTERS"

# Words that add nothing to a filename.
STOPWORDS = {"a", "an", "the", "and", "or", "of", "as", "is", "in", "on", "to", "not"}


def strip_tags(fragment):
    """Turn an HTML fragment into readable plain text."""
    text = re.sub(r"<[^>]+>", "", fragment)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def slugify(title, keep_stopwords=False, max_words=6):
    """'11. Pentatonic: the scale with no wrong notes' -> 'pentatonic-scale-no-wrong-notes'."""
    title = re.sub(r"^\s*\d+\.\s*", "", title)          # drop the leading number
    title = html.unescape(title).lower()
    title = title.replace("&", " and ")
    words = re.findall(r"[a-z0-9]+", title)
    if not keep_stopwords:
        words = [w for w in words if w not in STOPWORDS] or words
    return "-".join(words[:max_words])


def parse_syllabus(path):
    """Extract parts and lessons from the tracker HTML."""
    if not path.exists():
        sys.exit(f"Syllabus not found: {path}")
    doc = path.read_text(encoding="utf-8")

    parts = []
    part_re = re.compile(
        r'<section class="module" id="(?P<id>p\d+)">(?P<body>.*?)</section>', re.S
    )
    lesson_re = re.compile(
        r'<article class="lesson" data-keywords="(?P<kw>[^"]*)">(?P<body>.*?)</article>', re.S
    )

    for pm in part_re.finditer(doc):
        body = pm.group("body")
        heading = strip_tags(re.search(r"<h2>(.*?)</h2>", body, re.S).group(1))
        summary_m = re.search(r'<p class="module-summary">(.*?)</p>', body, re.S)
        summary = strip_tags(summary_m.group(1)) if summary_m else ""

        # 'Part 3. Rhythm and meter' -> number 3, name 'Rhythm and meter'
        hm = re.match(r"Part\s+(\d+)\.\s*(.+)", heading)
        if not hm:
            sys.exit(f"Unexpected part heading: {heading!r}")
        pnum, pname = int(hm.group(1)), hm.group(2).strip()

        lessons = []
        for lm in lesson_re.finditer(body):
            lb = lm.group("body")
            num = int(re.search(r'data-lesson="(\d+)"', lb).group(1))
            title = strip_tags(re.search(r"<h3>(.*?)</h3>", lb, re.S).group(1))
            duration = strip_tags(
                re.search(r'<div class="duration">(.*?)</div>', lb, re.S).group(1)
            )
            bullets = [strip_tags(b) for b in re.findall(r"<li>(.*?)</li>", lb, re.S)]

            payoff, payoff_kind = "", ""
            for kind in ("outcome", "checkpoint", "ear"):
                m = re.search(rf'<div class="{kind}">(.*?)</div>', lb, re.S)
                if m:
                    payoff, payoff_kind = strip_tags(m.group(1)), kind
                    break

            lessons.append(
                {
                    "num": num,
                    "title": title,
                    "duration": duration,
                    "keywords": lm.group("kw").split(),
                    "bullets": bullets,
                    "payoff": payoff,
                    "payoff_kind": payoff_kind,
                }
            )

        if lessons:
            parts.append(
                {
                    "num": pnum,
                    "name": pname,
                    "summary": summary,
                    "slug": f"{pnum:02d}-{slugify(pname, keep_stopwords=True)}",
                    "lessons": lessons,
                }
            )

    return parts


def lesson_path(part, lesson):
    return Path("parts") / part["slug"] / f"{lesson['num']:02d}-{slugify(lesson['title'])}.qmd"


def stub(part, lesson):
    """A lesson file with the syllabus notes carried across as a planning block."""
    concepts = ", ".join(lesson["keywords"][:6])
    planned = "\n".join(f"> - {b}" for b in lesson["bullets"])
    payoff = f"\n>\n> **{lesson['payoff']}**" if lesson["payoff"] else ""

    return f"""---
title: "{lesson['num']}. {lesson['title'].split('. ', 1)[-1]}"
subtitle: "{lesson['duration']}"
part: "{part['name']}"
concepts: [{concepts}]
sonic-pi: []
status: outline
---

::: {{.callout-note collapse="true" title="Planned, from the syllabus"}}
Delete this block once the lesson is drafted.

{planned}{payoff}
:::

## The idea

What the musical concept is and what it does to sound. Two or three paragraphs.
First person for me, second person for the reader, no encouragement. See
STYLE.md.

## Run this

```{{.ruby audio=""}}
# TODO
```

What you just heard, in a sentence or two.

## Change one thing

Two or three directed experiments. Each says what to change and what to listen
for.

## Why it works

The explanation, now that the sound is in your ears.

## Take it further

One optional harder exercise. Worked answer in the solutions appendix.
"""


def render_chapters(parts):
    lines = [BEGIN]
    lines.append("    - index.qmd")
    lines.append("    - setup.qmd")
    for part in parts:
        lines.append(f'    - part: "Part {part["num"]}. {part["name"]}"')
        lines.append("      chapters:")
        for lesson in part["lessons"]:
            lines.append(f"        - {lesson_path(part, lesson).as_posix()}")
    lines.append(END)
    return "\n".join(lines)


def render_solutions(parts):
    out = [
        "---",
        'title: "Solutions"',
        "---",
        "",
        "Worked answers to the *Take it further* exercise in each lesson. Work",
        "the exercise before reading. A solution you have not tried to reach",
        "teaches nothing.",
        "",
        "Sections marked TODO are waiting on their lesson to be drafted.",
        "",
    ]
    for part in parts:
        out.append(f"## Part {part['num']}. {part['name']}")
        out.append("")
        for lesson in part["lessons"]:
            out.append(f"### {lesson['num']}. {lesson['title'].split('. ', 1)[-1]}")
            out.append("")
            out.append("TODO")
            out.append("")
    return "\n".join(out)


def write(path, content, dry_run, created, updated, skipped):
    full = ROOT / path
    if full.exists():
        if full.read_text(encoding="utf-8") == content:
            skipped.append(path)
        else:
            updated.append(path)
            if not dry_run:
                full.write_text(content, encoding="utf-8")
    else:
        created.append(path)
        if not dry_run:
            full.parent.mkdir(parents=True, exist_ok=True)
            full.write_text(content, encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true", help="report changes, write nothing")
    ap.add_argument("--prune", action="store_true",
                    help="delete orphaned stubs left behind by a rename (outlines only)")
    args = ap.parse_args()

    parts = parse_syllabus(SYLLABUS)
    total = sum(len(p["lessons"]) for p in parts)
    print(f"Syllabus: {len(parts)} parts, {total} lessons")

    created, updated, skipped = [], [], []

    # Lesson stubs. Never overwrite a lesson that already has content.
    for part in parts:
        for lesson in part["lessons"]:
            path = lesson_path(part, lesson)
            if (ROOT / path).exists():
                skipped.append(path)
                continue
            created.append(path)
            if not args.dry_run:
                (ROOT / path).parent.mkdir(parents=True, exist_ok=True)
                (ROOT / path).write_text(stub(part, lesson), encoding="utf-8")

    # Chapter list, spliced into the handwritten config.
    if not CONFIG.exists():
        sys.exit(f"Missing {CONFIG}. Create it first; this script only fills in chapters.")
    config = CONFIG.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(config):
        sys.exit("_quarto.yml has no BEGIN/END CHAPTERS markers.")
    new_config = pattern.sub(lambda _: render_chapters(parts), config)
    if new_config != config:
        updated.append(Path("_quarto.yml"))
        if not args.dry_run:
            CONFIG.write_text(new_config, encoding="utf-8")
    else:
        skipped.append(Path("_quarto.yml"))

    # Solutions appendix, regenerated only while every entry is still TODO.
    solutions = render_solutions(parts)
    if SOLUTIONS.exists() and "TODO" not in SOLUTIONS.read_text(encoding="utf-8"):
        skipped.append(SOLUTIONS.relative_to(ROOT))
    else:
        write(SOLUTIONS.relative_to(ROOT), solutions, args.dry_run, created, updated, skipped)

    # Orphans: stub files left behind when a lesson is renamed in the syllabus.
    wanted = {ROOT / lesson_path(part, l) for part in parts for l in part["lessons"]}
    orphans = sorted(f for f in (ROOT / "parts").rglob("*.qmd") if f not in wanted)
    pruned, kept = [], []
    for f in orphans:
        untouched = "status: outline" in f.read_text(encoding="utf-8")
        if args.prune and untouched and not args.dry_run:
            f.unlink()
            pruned.append(f.relative_to(ROOT))
        elif untouched:
            kept.append((f.relative_to(ROOT), "outline, safe to prune"))
        else:
            kept.append((f.relative_to(ROOT), "HAS CONTENT, will never be pruned"))

    verb = "would create" if args.dry_run else "created"
    print(f"{verb}: {len(created)}, updated: {len(updated)}, unchanged: {len(skipped)}")
    for p in created[:5]:
        print(f"  + {p}")
    if len(created) > 5:
        print(f"  + ... and {len(created) - 5} more")
    for p in updated:
        print(f"  ~ {p}")
    if pruned:
        print(f"pruned {len(pruned)} orphaned stub(s):")
        for p in pruned:
            print(f"  - {p}")
    if kept:
        print(f"{len(kept)} orphan(s) left in place. Rerun with --prune to remove the outlines:")
        for p, why in kept:
            print(f"  ? {p}  ({why})")
    # Empty part directories left over from a renamed part.
    for d in sorted((ROOT / "parts").iterdir()):
        if d.is_dir() and not any(d.iterdir()):
            if args.prune and not args.dry_run:
                d.rmdir()
                print(f"  - {d.relative_to(ROOT)}/ (empty)")


if __name__ == "__main__":
    main()
